# User
user.email.already.exists=An account with this email already exists
user.credentials.invalid=Invalid email or password
user.not.found=User not found

# Task list
task.list.not.found=Task list not found

# Task
task.not.found=Task not found

# Subtask
subtask.not.found=Subtask not found

# Email
email.token.invalid.or.unknown=Invalid or unknown token
email.token.invalid.token.type=Invalid token type
email.token.already.been.used=Token has already been used
email.token.has.expired=Token has expired
email.not.verified=Email address has not been verified

# Security
security.sha.256.not.available=SHA-256 not available

# Encryption
encryption.failed=An error occurred processing your data
